### ISSUE TITLE
p10 led module not working using this library

### ISSUE THREAD

**Issue by Vibinreji** [Qudor-Engineer/DMD32#2]
Hi,   
    I have used this library for scrolling text on p10 led board using esp32.i used this libarary.i have used the code from example section from this repositary.But when i upload the code to esp32 the LED board glowing randomly.3 or 4 LED bulbs randomly glowing in p10 LED board.Is this issue of hardware setup or coding issue any idea?

**Comment by Qudor-Engineer** [comment]
I guess you have connections problems. I already done many projects with my library it is working fine

**Comment by Vibinreji** [comment]
Yes it has connection wire problem.Now its working fine.Thanks
