### ISSUE TITLE
Use Library on HUB 08 or HUB 75 Led Display

### ISSUE THREAD

**Issue by ashadyiman** [Qudor-Engineer/DMD32#9]
can i use this library on led display with HUB 08 or HUB 75? the pin is similar but there is a different in SCLK pin on dmd and LAT/STB pin on Hub08 or Hub75.

**Comment by Qudor-Engineer** [comment]
Refer to the original DMD library (https://github.com/freetronics/DMD) if it support HUB then DMD32 should be as well.

**Comment by budi-s** [comment]
I don't think this library works for HUB08 or HUB75 because it has different scan rate and pinout. You need to modify this (or the original one) to work with those.
